<a href="https://colab.research.google.com/github/PhongCT1105/TSFM-Introduction/blob/main/TSFM_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd

df_mo = pd.read_csv("monthly_detections_frontex.csv")
df_mo

,Route,Border type or inland,Nationality,Jan-09,Feb-09,Mar-09,Apr-09,May-09,Jun-09,Jul-09,...,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24
0,Eastern Mediterranean Route,Sea,Afghanistan,770,564,779,1067,1336,1454,1326,...,2201,620,725,717,581,407,675,623,1554,2788
1,Eastern Mediterranean Route,Sea,Syria,9,16,20,10,11,16,22,...,1419,1588,1445,1633,1144,2200,3140,3304,2748,1866
2,Eastern Mediterranean Route,Sea,Egypt,0,0,7,0,1,1,0,...,535,324,252,433,332,554,758,802,928,627
3,Eastern Mediterranean Route,Sea,Unknown,9,1,0,0,0,0,0,...,0,11,0,0,0,0,4,660,250,407
4,Eastern Mediterranean Route,Sea,Eritrea,16,28,68,66,65,140,153,...,60,74,131,202,29,192,233,289,379,214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,Other,Sea,Syria,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
876,Other,Sea,TÃ¼rkiye,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
877,Other,Sea,United Kingdom,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
878,Other,Sea,United States,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
879,Other,Sea,Unknown,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df_pro = pd.read_csv("processed_data_frontex.csv")
df_pro

,Period,us_cpi,Afghanistan_gdp,Albania_gdp,Benin_gdp,Burkina Faso_gdp,Bangladesh_gdp,Cameroon_gdp,Dominican Republic_gdp,Algeria_gdp,...,Nepal_cpi,Pakistan_cpi,Sudan_cpi,Senegal_cpi,Sierra Leone_cpi,Chad_cpi,Togo_cpi,Tunisia_cpi,commodity,Stock_Close
0,2009-01,211.143000,452.053705,4114.134033,1024.102779,601.569521,679.211477,1461.389992,4977.798844,4235.429905,...,11.094824,13.647765,11.256759,0.0,7.469019,9.952423,3.713606,3.664903,102.098634,932.45
1,2009-02,212.193000,461.274532,4112.453719,1019.783288,603.555876,685.850896,1456.056041,5020.846169,4292.958767,...,10.944638,13.587558,11.402918,0.0,7.444953,8.930672,3.521010,3.637222,105.417768,833.84
2,2009-03,212.709000,469.603021,4110.936015,1015.881812,605.350003,691.847791,1451.238279,5059.727624,4344.920319,...,10.808986,13.533177,11.534933,0.0,7.423216,8.007801,3.347053,3.612220,108.415696,897.66
3,2009-04,213.240000,478.823848,4109.255701,1011.562321,607.336359,698.487210,1445.904328,5102.774949,4402.449180,...,10.658800,13.472969,11.681092,0.0,7.399150,6.986050,3.154457,3.584539,111.734830,996.08
4,2009-05,213.856000,487.747229,4107.629590,1007.382168,609.258638,704.912454,1440.742440,5144.433650,4458.122272,...,10.513458,13.414704,11.822537,0.0,7.375861,5.997260,2.968074,3.557750,114.268484,1085.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,2024-11,315.493000,522.992341,11748.483857,1632.389686,968.177231,2247.281579,1979.132252,11833.873864,6102.818361,...,6.130810,50.765826,0.000000,0.0,85.152933,20.103154,18.690056,11.205978,167.217697,4164.54
191,2024-12,315.605000,527.796143,11890.572487,1643.047136,972.005026,2233.681453,1989.980223,11883.855037,6135.898528,...,6.086752,51.661245,0.000000,0.0,86.832488,20.518086,19.000853,11.290021,168.021406,4061.81
192,2025-03,315.941000,542.207551,12316.838375,1675.019486,983.488411,2192.881075,2022.524134,12033.798556,6235.139031,...,5.954580,54.347503,0.000000,0.0,91.871153,21.762879,19.933242,11.542153,170.432531,4073.03
193,2025-02,315.836467,537.724002,12184.222321,1665.072533,979.915802,2205.574526,2012.399362,11987.149461,6204.264208,...,5.995700,53.511778,0.000000,0.0,90.303568,21.375610,19.643166,11.463712,169.682403,4174.72
194,2025-01,315.720733,532.760072,12037.397404,1654.059834,975.960414,2219.627989,2001.189792,11935.502249,6170.081368,...,6.041226,52.586512,0.000000,0.0,88.568028,20.946848,19.322009,11.376867,168.851904,4192.34

In [36]:
df_pro.columns

Index(['Period', 'us_cpi', 'Afghanistan_gdp', 'Albania_gdp', 'Benin_gdp',
       'Burkina Faso_gdp', 'Bangladesh_gdp', 'Cameroon_gdp',
       'Dominican Republic_gdp', 'Algeria_gdp',
       ...
       'Nepal_cpi', 'Pakistan_cpi', 'Sudan_cpi', 'Senegal_cpi',
       'Sierra Leone_cpi', 'Chad_cpi', 'Togo_cpi', 'Tunisia_cpi', 'commodity',
       'Stock_Close'],
      dtype='object', length=158)

### I. Feature engineering

In [24]:
df_mo.columns

Index(['Route', 'Border type or inland', 'Nationality', 'Jan-09', 'Feb-09',
       'Mar-09', 'Apr-09', 'May-09', 'Jun-09', 'Jul-09',
       ...
       'Feb-24', 'Mar-24', 'Apr-24', 'May-24', 'Jun-24', 'Jul-24', 'Aug-24',
       'Sep-24', 'Oct-24', 'Nov-24'],
      dtype='object', length=194)

In [34]:
# Drop and agg monthly dataset

df_mo = df_mo[df_mo["Route"] == "Eastern Mediterranean Route"]
df_mo = df_mo.drop(columns=["Border type or inland", "Nationality"])
df_mo = df_mo.groupby("Route").agg(["sum"])
df_mo

,Jan-09,Feb-09,Mar-09,Apr-09,May-09,Jun-09,Jul-09,Aug-09,Sep-09,Oct-09,...,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24
,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum
Route,,,,,,,,,,,,,,,,,,,,,
Eastern Mediterranean Route,2730,2228,2870,3298,3750,3880,3920,4272,3979,3969,...,5355,3890,3868,4685,3631,5596,7501,8757,9139,8200

### II. SARIMAX Modelling

,Jan-09,Feb-09,Mar-09,Apr-09,May-09,Jun-09,Jul-09,Aug-09,Sep-09,Oct-09,...,Feb-24,Mar-24,Apr-24,May-24,Jun-24,Jul-24,Aug-24,Sep-24,Oct-24,Nov-24
,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,sum
Route,,,,,,,,,,,,,,,,,,,,,
Eastern Mediterranean Route,2730,2228,2870,3298,3750,3880,3920,4272,3979,3969,...,5355,3890,3868,4685,3631,5596,7501,8757,9139,8200